sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t greenimage .
  - docker ps -a
  - docker run greenimage /bin/sh -c "ant; ant test"

script:
  - ant;
  - ant test;
